### ISSUE TITLE
Default export not working after updating to 2.0.0

### ISSUE THREAD

**Issue by ettoredn** [pd4d10/vite-plugin-svgr#32]
```
import {defineConfig, searchForWorkspaceRoot, UserConfig} from 'vite'
import react from '@vitejs/plugin-react'
import * as path from "path";
import svgr from 'vite-plugin-svgr';

export default defineConfig(({command, mode}) => {
  const config = {
    ....
    plugins: [react(), svgr()],
   ....
  } as UserConfig;

  return config;
})
```

```
failed to load config from /Users/ettore/Workspace/conagrivet/api/vite.config.ts
error when starting dev server:
TypeError: svgr is not a function
    at file:///Users/ettore/Workspace/conagrivet/api/vite.config.ts.js?t=1651562275412:12:24
```

Doing a `console.debug(svgr)` it shows an object with a `default` property. Does this have something to do with CommonJS transpilation? I see lib/index.js uses `exports.default` instead of ESM.

**Comment by pd4d10** [comment]
Thanks for the feedback, but it seems to work as expected in my local machine.

Could you please provide a minimal reproduction repo?

**Comment by ettoredn** [comment]
I will as soon as I can. Is it maybe because I'm using `"type": "module",` in the package.json of my project?

**Comment by pd4d10** [comment]
Published v2.1.0 to fix this.

Thanks for the report!
